insert into diplome(id, domaine_id, name, ordre) values (1, 2, "L’ANNÉE DE PRÉPARATION AUX ÉTUDES SCIENTIFIQUES", 10);
insert into diplome(id, domaine_id, name, ordre) values (2, 2, "LICENCE BIOLOGIE : SCIENCES DE LA VIE", 20);
insert into diplome(id, domaine_id, name, ordre) values (3, 2, "LICENCE SCIENCES POUR L’INGÉNIEUR", 30);
insert into diplome(id, domaine_id, name, ordre) values (4, 2, "LICENCE SCIENCES DU NUMÉRIQUE", 40);
insert into diplome(id, domaine_id, name, ordre) values (5, 2, "LICENCE TECHNOLOGIES & DÉVELOPPEMENT DURABLE", 50);
insert into diplome(id, domaine_id, name, ordre) values (6, 2, "LICENCE MANAGEMENT & NUMÉRIQUE", 60);
insert into diplome(id, domaine_id, name, ordre) values (7, 2, "MASTER INFORMATIQUE CYBER", 70);
insert into diplome(id, domaine_id, name, ordre) values (8, 2, "MASTER ÉCOLOGIE OPÉRATIONNELLE", 80);
insert into diplome(id, domaine_id, name, ordre) values (9, 2, "MASTER DIGITAL COMMERCE", 90);
insert into diplome(id, domaine_id, name, ordre) values (10, 2, "MASTER COMMUNICATION NUMÉRIQUE", 100);
insert into diplome(id, domaine_id, name, ordre) values (11, 2, "MASTER DATA & INTELLIGENCE ARTIFICIELLE", 110);