insert into matiere(id, semestre_id, name, enseignant_d) values (1, 17, "Intelligence artificielle", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (2, 17, "Cybersécurité", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (3, 17, "DevOps", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (4, 17, "Gestion de projet Agile", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (5, 17, "Programmation par composant 1", "sixd");
insert into matiere(id, semestre_id, name, enseignant_d) values (6, 17, "Programmation fonctionnelle", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (7, 17, "UX Design", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (8, 17, "Ac’LAB", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (9, 17, "Technologies d’entreprise", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (10, 17, "Droit et données", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (11, 17, "English for computer science", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (12, 17, "Évaluation de la période en entreprise", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (13, 18, "Test et qualité logicielle", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (14, 18, "Programmation objet avancée", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (15, 18, "Programmation par composant 2", "sixd");
insert into matiere(id, semestre_id, name, enseignant_d) values (16, 18, "Programmation fonctionnelle 2", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (17, 18, "Développement mobile", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (18, 18, "Cybersécurité", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (19, 18, "English for computer science 2", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (20, 18, "Ac’LAB", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (21, 18, "Technologies d’entreprise", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (22, 18, "Mémoire d’alternance", "");
insert into matiere(id, semestre_id, name, enseignant_d) values (23, 18, "Évaluation de la période en entreprise", "");
